// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGYq8ler13fBSGZaZWa-i1XJ7ssda8S1A',
    appId: '1:45704073545:web:92299ee88378c071200a98',
    messagingSenderId: '45704073545',
    projectId: 'game-chat-b80b7',
    authDomain: 'game-chat-b80b7.firebaseapp.com',
    storageBucket: 'game-chat-b80b7.appspot.com',
    measurementId: 'G-CEKGX4V2CH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQabQFgzAfi3vcfe5fimuYqZFobCKXh1o',
    appId: '1:45704073545:android:28842807f4eb523f200a98',
    messagingSenderId: '45704073545',
    projectId: 'game-chat-b80b7',
    storageBucket: 'game-chat-b80b7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfzndcREDMb7GE-XmW-v6_m1aJqtuVtOA',
    appId: '1:45704073545:ios:948e2fbd1e720603200a98',
    messagingSenderId: '45704073545',
    projectId: 'game-chat-b80b7',
    storageBucket: 'game-chat-b80b7.appspot.com',
    iosClientId: '45704073545-v1bngbgmupvtqqoi2hbsl0n33nrlt17m.apps.googleusercontent.com',
    iosBundleId: 'com.example.gameChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfzndcREDMb7GE-XmW-v6_m1aJqtuVtOA',
    appId: '1:45704073545:ios:edb9d77198eba216200a98',
    messagingSenderId: '45704073545',
    projectId: 'game-chat-b80b7',
    storageBucket: 'game-chat-b80b7.appspot.com',
    iosClientId: '45704073545-t027r3dgsv946kp8s33lmtd4sc50ddr3.apps.googleusercontent.com',
    iosBundleId: 'com.example.gameChat.RunnerTests',
  );
}
